# Generated by Django 3.2.13 on 2022-10-07 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
